Basic API
dweill/villainary pull request #21
Opened 2024-01-23 19:58 UTC by christophermbooth

This adds a basic asp net core api.  The API is not secured and only has one endpoint at the moment for fetching a static list of products.

2024-01-26 16:01 UTC, dweill requested changes

2024-01-26 17:05 UTC, christophermbooth commented on backends/villainary_csharp/villainary_api/Controllers/ProductController.cs
> +            Console.WriteLine("GetProducts action called");
No that was for logging purposes while testing the connection from the next docker container.  Removed.

2024-01-28 13:43 UTC, dweill commented on villainary-react/Dockerfile
> +ENV API_HOST=${API_HOST:-villainary-csharp}
tightly coupling.

2024-01-28 13:44 UTC, dweill approved these changes

2024-01-28 23:41 UTC, merged